import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    search: 'Search products, brands and more...',
    searchBtn: 'Search',
    wishlist: 'Wishlist',
    cart: 'Cart',
    more: 'More',
    home: 'Home',
    products: 'Products',
    deals: 'Deals',
    about: 'About',
    login: 'Login',
    logout: 'Logout',
    myAccount: 'My Account',
    adminDashboard: 'Admin Dashboard',
    aboutUs: 'About Us',
    flashDeals: '⚡ Flash Deals',
    endsIn: 'Ends in',
    viewAll: 'View All →',
    hotDeals: '🔥 Hot Deals',
    shopNow: 'Shop Now →',
    viewDeals: 'View Deals',
    addToCart: 'Add to Cart',
    signIn: 'Sign In',
    welcomeBack: 'Welcome back! Please sign in.',
    password: 'Password',
    qrCode: 'QR Code',
    emailAddress: 'Email Address',
    passwordLabel: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signInBtn: 'Sign In',
    signingIn: 'Signing in...',
    orContinueWith: 'or continue with',
    continueWithGoogle: 'Continue with Google',
    noAccount: "Don't have an account?",
    createOne: 'Create one',
    footerTagline: 'Your trusted online store for quality products at unbeatable prices. Fast delivery across Rwanda.',
    footerCompany: 'Company',
    footerContactUs: 'Contact Us',
    footerHowToBuy: 'How To Buy',
    footerReturns: 'Returns & Refunds Policy',
    footerShop: 'Shop',
    footerOrders: 'Orders',
    footerCustomerService: 'Customer Service',
    footerProfile: 'Profile',
    footerSupport: 'Customer Support',
    footerTerms: 'Terms of Service',
    footerPrivacy: 'Privacy Policy',
    footerRights: 'All rights reserved.',
    footerAddress: 'Kicukiro – Kanombe, Rwanda',
  },
  rw: {
    search: 'Shakisha ibicuruzwa, amasoko...',
    searchBtn: 'Shakisha',
    wishlist: 'Ibifuzo',
    cart: 'Agasanduku',
    more: 'Ibindi',
    home: 'Ahabanza',
    products: 'Ibicuruzwa',
    deals: 'Amangazo',
    about: 'Abo turi bo',
    login: 'Injira',
    logout: 'Sohoka',
    myAccount: 'Konti Yanjye',
    adminDashboard: "Ikibaho cy'Ubuyobozi",
    aboutUs: 'Abo Turi Bo',
    flashDeals: '⚡ Amangazo Vuba',
    endsIn: 'Irangira mu',
    viewAll: 'Reba Byose →',
    hotDeals: '🔥 Amangazo Ashyushye',
    shopNow: 'Gura Ubu →',
    viewDeals: 'Reba Amangazo',
    addToCart: 'Shyira mu Gasanduku',
    signIn: 'Injira',
    welcomeBack: 'Murakaza neza! Injira muri konti yawe.',
    password: 'Ijambo Banga',
    qrCode: 'QR Code',
    emailAddress: 'Imeyili',
    passwordLabel: 'Ijambo Banga',
    rememberMe: 'Nzibutse',
    forgotPassword: 'Wibagiwe ijambo banga?',
    signInBtn: 'Injira',
    signingIn: 'Injira...',
    orContinueWith: 'cyangwa komeza na',
    continueWithGoogle: 'Komeza na Google',
    noAccount: 'Nta konti ufite?',
    createOne: 'Fungura',
    footerTagline: "Iduka ryawe ry'internet ry'ibicuruzwa byiza ku giciro gikwiye. Gutanga vuba mu Rwanda hose.",
    footerCompany: 'Sosiyete',
    footerContactUs: 'Twandikire',
    footerHowToBuy: 'Uburyo bwo Kugura',
    footerReturns: 'Gusubiza no Gusubizwa Amafaranga',
    footerShop: 'Iduka',
    footerOrders: 'Ibyo Watumye',
    footerCustomerService: "Serivisi z'Abakiriya",
    footerProfile: 'Umwirondoro',
    footerSupport: "Inkunga y'Abakiriya",
    footerTerms: "Amategeko y'Serivisi",
    footerPrivacy: "Politiki y'Ibanga",
    footerRights: 'Uburenganzira bwose bwabitswe.',
    footerAddress: 'Kicukiro – Kanombe, u Rwanda',
  },
  fr: {
    search: 'Rechercher produits, marques...',
    searchBtn: 'Rechercher',
    wishlist: 'Favoris',
    cart: 'Panier',
    more: 'Plus',
    home: 'Accueil',
    products: 'Produits',
    deals: 'Offres',
    about: 'À propos',
    login: 'Connexion',
    logout: 'Déconnexion',
    myAccount: 'Mon Compte',
    adminDashboard: 'Tableau de Bord',
    aboutUs: 'À Propos',
    flashDeals: '⚡ Ventes Flash',
    endsIn: 'Se termine dans',
    viewAll: 'Voir Tout →',
    hotDeals: '🔥 Meilleures Offres',
    shopNow: 'Acheter →',
    viewDeals: 'Voir les Offres',
    addToCart: 'Ajouter au Panier',
    signIn: 'Connexion',
    welcomeBack: 'Bon retour! Veuillez vous connecter.',
    password: 'Mot de passe',
    qrCode: 'QR Code',
    emailAddress: 'Adresse e-mail',
    passwordLabel: 'Mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié?',
    signInBtn: 'Se connecter',
    signingIn: 'Connexion...',
    orContinueWith: 'ou continuer avec',
    continueWithGoogle: 'Continuer avec Google',
    noAccount: 'Pas de compte?',
    createOne: 'Créer un compte',
    footerTagline: 'Votre boutique en ligne de confiance pour des produits de qualité. Livraison rapide partout au Rwanda.',
    footerCompany: 'Entreprise',
    footerContactUs: 'Contactez-nous',
    footerHowToBuy: 'Comment Acheter',
    footerReturns: 'Politique de Retour & Remboursement',
    footerShop: 'Boutique',
    footerOrders: 'Commandes',
    footerCustomerService: 'Service Client',
    footerProfile: 'Profil',
    footerSupport: 'Support Client',
    footerTerms: "Conditions d'Utilisation",
    footerPrivacy: 'Politique de Confidentialité',
    footerRights: 'Tous droits réservés.',
    footerAddress: 'Kicukiro – Kanombe, Rwanda',
  },
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en')
  const t = translations[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)

export const useCatName = () => {
  const { lang } = useContext(LanguageContext)
  return (cat) => {
    if (!cat) return ''
    if (lang === 'rw' && cat.nameRw) return cat.nameRw
    if (lang === 'fr' && cat.nameFr) return cat.nameFr
    return cat.name
  }
}
